### ISSUE TITLE
chrome-extension Error

### ISSUE THREAD

**Issue by zhangzhengyi12** [lavas-project/hexo-pwa#3]
He works great, but the only problem is that the console has been outputting such errors, do you know why?

` /sw.js?t=1515437173661:14 Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at /sw.js?t=1515437173661:14
    at <anonymous> `

**Comment by PengXing** [comment]
`chrome-extension://xxx` protocol is unsupported by service worker. And there is no need to catch these kinds of request. So, just ignore those errors.
