### ISSUE TITLE
how to exclude ressource/script ?

### ISSUE THREAD

**Issue by JOduMonT** [lavas-project/hexo-pwa#6]
Hi;

I know it's probably more a question for sw team but, just in case you know how and/or you already have a trick for me

Do you know how I could exclude ressource/script ?
because I have a [quota exceeded error](https://developers.google.com/web/updates/2017/10/quotaexceedederror) when I use your plugins with disqus

so I would like to understand how to exlude disqus js

I also found [this](https://github.com/GoogleChromeLabs/sw-precache/issues/97)

**Comment by PengXing** [comment]
I don't think there is an exclusion problem with this plugin, as it doesn't include resource/scripts but **posts** in the pre-cache list while compiling.

*Please feel free to reopen this issue if needed.*
